# Generated by Django 5.1.6 on 2025-02-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_submission',
            field=models.BooleanField(default=False),
        ),
    ]
