# Generated by Django 5.1.7 on 2025-03-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacher_ref_id',
            new_name='reference_id',
        ),
    ]
