# Generated by Django 5.1.7 on 2025-03-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0002_rename_teacher_ref_id_teacherprofile_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='default_folder/default_student.jpg', upload_to='student_profiles/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(default='default_folder/default_teacher.jpg', upload_to='teacher_profiles/'),
        ),
    ]
