# Generated by Django 5.1.7 on 2025-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0002_rename_assigned_class_assignment_joined_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms', to='classmanagement.studentprofile'),
        ),
    ]
