# Generated by Django 5.1.7 on 2025-03-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0003_alter_studentprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='reference_id',
        ),
    ]
