# Generated by Django 5.1.7 on 2025-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0003_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='joined_classes',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_classes', to='classmanagement.studentprofile'),
        ),
    ]
