# Generated by Django 5.1.7 on 2025-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0004_remove_studentprofile_joined_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='plagiarism_active',
            field=models.BooleanField(default=False),
        ),
    ]
