# Generated by Django 5.1.7 on 2025-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0004_remove_teacherprofile_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
