# Generated by Django 5.1.7 on 2025-03-17 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0005_teacherprofile_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='assigned_students', to='classmanagement.classroom'),
        ),
    ]
