# Generated by Django 5.1.7 on 2025-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0006_classroom_created_at_classroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='default_folder/default_student.jpg', upload_to='profile_pics/'),
        ),
    ]
