# Generated by Django 5.1.7 on 2025-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0007_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joined_classes',
            field=models.ManyToManyField(related_name='students_joined', to='classmanagement.classroom'),
        ),
    ]
