# Generated by Django 5.1.7 on 2025-03-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0007_remove_classroom_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='joined_classes',
            new_name='classroom',
        ),
    ]
