# Generated by Django 5.1.7 on 2025-03-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0008_rename_joined_classes_assignment_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='classroom',
            new_name='joined_classes',
        ),
    ]
