# Generated by Django 5.1.7 on 2025-03-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0008_studentprofile_joined_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='assigned_classes',
        ),
    ]
