# Generated by Django 5.1.7 on 2025-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0009_rename_classroom_assignment_joined_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_classes_set', to='classmanagement.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_classes',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='classmanagement.classroom'),
        ),
    ]
