# Generated by Django 5.1.7 on 2025-03-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0010_classroom_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_classes',
            field=models.ManyToManyField(blank=True, related_name='joined_students', to='classmanagement.classroom'),
        ),
    ]
