# Generated by Django 5.1.6 on 2025-02-23 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0011_alter_customuser_teacher_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Submitted_assignments',
            field=models.ManyToManyField(blank=True, related_name='student_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
