# Generated by Django 5.1.6 on 2025-02-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0012_assignment_submitted_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Submitted_assignments',
            new_name='submitted_assignments',
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classmanagement.assignment'),
        ),
    ]
