# Generated by Django 5.1.7 on 2025-03-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0014_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='word_frequencies',
            field=models.JSONField(default=dict),
        ),
    ]
