# Generated by Django 5.1.7 on 2025-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0015_submission_word_frequencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='keyword_match',
            field=models.FloatField(default=0.0),
        ),
    ]
