# Generated by Django 5.1.7 on 2025-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0017_alter_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grammar_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
