# Generated by Django 5.1.6 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reference_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
