# Generated by Django 5.1.7 on 2025-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0018_submission_grammar_score_alter_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
