# Generated by Django 5.1.6 on 2025-03-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0019_alter_studentprofile_student_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classroom',
        ),
    ]
