# Generated by Django 5.1.7 on 2025-03-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0019_submission_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms_joined', to='classmanagement.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_classes',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='classmanagement.classroom'),
        ),
    ]
