# Generated by Django 5.1.7 on 2025-03-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0020_classroom_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='joined_classes',
            new_name='enrolled_classes',
        ),
    ]
