# Generated by Django 5.1.6 on 2025-03-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0021_customuser_assigned_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_class',
        ),
    ]
