# Generated by Django 5.1.7 on 2025-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0021_rename_joined_classes_studentprofile_enrolled_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_classes',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='joined_classes',
            field=models.ManyToManyField(blank=True, related_name='joined_students', to='classmanagement.classroom'),
        ),
    ]
