# Generated by Django 5.1.7 on 2025-04-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0024_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
