# Generated by Django 5.1.7 on 2025-04-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0025_performance_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='average_score',
        ),
    ]
