# Generated by Django 5.1.7 on 2025-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0027_remove_assignment_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extracted_image',
            field=models.ImageField(blank=True, null=True, upload_to='extracted_images/'),
        ),
    ]
