# Generated by Django 5.1.7 on 2025-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0028_assignment_extracted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
