# Generated by Django 5.1.7 on 2025-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0029_assignment_extracted_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='keyword_match',
            new_name='content_match',
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(default='default_folder/default_teacher.jpg', upload_to='profile_pics/'),
        ),
    ]
