# Generated by Django 5.1.7 on 2025-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0031_submission_preprocessed_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='extracted_text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='assignment',
            name='processed_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
