# Generated by Django 5.1.7 on 2025-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0032_rename_extracted_text_assignment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='text_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
