# Generated by Django 5.1.7 on 2025-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0033_submission_image_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
    ]
