# Generated by Django 5.1.7 on 2025-04-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0034_submission_reference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='extracted_images',
        ),
    ]
