# Generated by Django 5.1.7 on 2025-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0035_remove_submission_extracted_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reference_image',
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
