# Generated by Django 5.1.7 on 2025-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0036_remove_submission_reference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='extracted_images',
            field=models.ImageField(blank=True, null=True, upload_to='extracted_student_images/'),
        ),
    ]
