# Generated by Django 5.1.7 on 2025-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0037_submission_image_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content_match',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='word_frequencies',
        ),
        migrations.AddField(
            model_name='assignment',
            name='extracted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
