# Generated by Django 5.1.7 on 2025-04-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0038_remove_assignment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmanagement.studentprofile')),
            ],
        ),
    ]
