# Generated by Django 5.1.7 on 2025-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0039_alter_submission_comments_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='submission',
            name='final_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='provisional_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
