# Generated by Django 5.1.7 on 2025-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0040_remove_submission_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_after_plagiarism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_before_plagiarism',
            field=models.TextField(blank=True, null=True),
        ),
    ]
