# Generated by Django 5.1.7 on 2025-04-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0041_submission_feedback_after_plagiarism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
    ]
