# Generated by Django 5.1.7 on 2025-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0042_remove_submission_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='grade',
            new_name='grade_before_plagiarism',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade_after_plagiarism',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
